ae.o: ae.c ae.h zmalloc.h ae_kqueue.c ae_epoll.c ae_select.c ae_evport.c
ae_epoll.o: ae_epoll.c
ae_evport.o: ae_evport.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h
common.o: common.c
endianconv.o: endianconv.c
latency.o: latency.c latency.h
main.o: main.c main.h ae.h latency.h
