main.o: main.c main.h
ae.o: ae.c ae.h zmalloc.h ae_kqueue.c ae_epoll.c ae_select.c ae_evport.c
ae_epoll.o: ae_epoll.c
ae_evport.o: ae_evport.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
zmalloc.o: zmalloc.c zmalloc.h
anet.o : anet.h anet.c fmacros.h
intset.o: intset.h intset.c endianconv.h
